In [1]:
# Import Dependencies

import pandas as pd
from sqlalchemy import create_engine
import psycopg2
import datetime as dt

In [3]:
# Import URL & Tables

url1 = "https://www.cdc.gov/mmwr/volumes/70/ss/ss7009a1.htm"
    
tables = pd.read_html(url1)

tables

[   Year Selected reporting areas§ Continuously reporting areas¶
    Year                       No.                     No. (%)**  Rate Ratio
 0  2010                    765651                762,755 (99.6)  14.4   225
 1  2011                    730322                727,554 (99.6)  13.7   217
 2  2012                    699202                696,587 (99.6)  13.1   208
 3  2013                    664435                661,874 (99.6)  12.4   198
 4  2014                    652639                649,849 (99.6)  12.1   192
 5  2015                    638169                636,902 (99.8)  11.8   188
 6  2016                    623471               623,471 (100.0)  11.6   186
 7  2017                    612719                609,095 (99.4)  11.2   185
 8  2018                    619591                614,820 (99.2)  11.3   189
 9  2019                    629898                625,346 (99.3)  11.4   195,
               State/Area Abortions reported by area of occurrence**        \
               State/Area                                        No.  Rate
 0                Alabama                                       6009   6.3
 1                 Alaska                                       1270   8.8
 2                Arizona                                      13097   9.4
 3               Arkansas                                       2963   5.1
 4               Colorado                                       9002   7.6
 5            Connecticut                                       9202  13.7
 6               Delaware                                       2042  11.3
 7   District of Columbia                                       4552  23.9
 8                Florida                                      71914  18.5
 9                Georgia                                      36907  16.9
 10                Hawaii                                       2003   7.6
 11                 Idaho                                       1513   4.4
 12              Illinois                                      46517  18.6
 13               Indiana                                       7637   5.8
 14                  Iowa                                       3566   6.0
 15                Kansas                                       6894  12.3
 16              Kentucky                                       3664   4.3
 17             Louisiana                                       8144   8.8
 18                 Maine                                       2021   8.7
 19         Massachusetts                                      18593  13.3
 20              Michigan                                      27339  14.6
 21             Minnesota                                       9940   9.2
 22           Mississippi                                       3194   5.5
 23              Missouri                                       1471   1.2
 24               Montana                                       1568   8.0
 25              Nebraska                                       2068   5.5
 26                Nevada                                       8414  14.0
 27          New Jersey††                                      22178  13.2
 28            New Mexico                                       3942   9.9
 29              New York                                      78587  20.3
 30         New York City                                      49784  27.2
 31        New York State                                      28803  14.1
 32        North Carolina                                      28450  13.8
 33          North Dakota                                       1121   7.6
 34                  Ohio                                      20102   9.1
 35              Oklahoma                                       4995   6.4
 36                Oregon                                       8688  10.5
 37          Pennsylvania                                      31018  13.0
 38          Rhode Island                                       2099  10.1
 39        South Carolina                                       5101   5.2
 40          South Dakota                                        414   2.6
 41             Tennessee                                       9719   7.3
 42                 Texas                                      57275   9.5
 43                  Utah                                       2922   4.2
 44               Vermont                                       1195  10.4
 45              Virginia                                      15601   9.2
 46            Washington                                      17262  11.4
 47         West Virginia                                       1183   3.8
 48             Wisconsin                                       6511   6.0
 49               Wyoming                                         31   0.3
 50                 Total                                     629898   NaN

           Abortions obtained by out-of-state residents
     Ratio                                      No. (%)
 0   103.0                                 1,040 (17.3)
 1   129.0                                     19 (1.5)
 2   165.0                                     67 (0.5)
 3    81.0                                   338 (11.4)
 4   143.0                                   946 (10.5)
 5   269.0                                    334 (3.6)
 6   193.0                                   277 (13.6)
 7   501.0                                 3,126 (68.7)
 8   327.0                                  2,256 (3.1)
 9   292.0                                 6,500 (17.6)
 10  119.0                                     49 (2.4)
 11   69.0                                     78 (5.2)
 12  332.0                                 7,534 (16.2)
 13   94.0                                    618 (8.1)
 14   95.0                                   490 (13.7)
 15  195.0                                 3,372 (48.9)
 16   69.0                                   643 (17.5)
 17  138.0                                 1,358 (16.7)
 18  172.0                                    107 (5.3)
 19  269.0                                    631 (3.4)
 20  253.0                                  1,435 (5.2)
 21  151.0                                    888 (8.9)
 22   87.0                                   335 (10.5)
 23   20.0                                    128 (8.7)
 24  142.0                                   169 (10.8)
 25   84.0                                   267 (12.9)
 26  240.0                                    434 (5.2)
 27  223.0                                  1,309 (5.9)
 28  172.0                                   939 (23.8)
 29  355.0                                  6,989 (8.9)
 30  472.0                                  4,668 (9.4)
 31  248.0                                  2,321 (8.1)
 32  240.0                                 5,079 (17.9)
 33  107.0                                   289 (25.8)
 34  150.0                                  1,186 (5.9)
 35  102.0                                    407 (8.1)
 36  208.0                                    795 (9.2)
 37  231.0                                  2,222 (7.2)
 38  206.0                                   274 (13.1)
 39   89.0                                    312 (6.1)
 40   36.0                                    82 (19.8)
 41  121.0                                 1,823 (18.8)
 42  152.0                                  1,303 (2.3)
 43   62.0                                    146 (5.0)
 44  223.0                                   265 (22.2)
 45  160.0                                    867 (5.6)
 46  203.0                                    848 (4.9)
 47   65.0                                   168 (14.2)
 48  103.0                                    139 (2.1)
 49    5.0                                     5 (16.1)
 50    NaN                                          NaN  ,
               State/Area Age group (yrs)                                \
               State/Area             <15         15–19           20–24
               State/Area        No. (%)†       No. (%)         No. (%)
 0                Alabama        23 (0.4)     526 (8.8)    1,807 (30.1)
 1                 Alaska              —¶     123 (9.7)      351 (27.6)
 2                Arizona        19 (0.1)   1,163 (8.9)    3,932 (30.0)
 3               Arkansas        10 (0.3)     294 (9.9)      892 (30.1)
 4               Colorado        27 (0.3)     812 (9.0)    2,596 (28.9)
 5            Connecticut        20 (0.2)     788 (8.7)    2,382 (26.3)
 6               Delaware         8 (0.4)    240 (11.8)      575 (28.2)
 7   District of Columbia        10 (0.2)     386 (8.5)    1,262 (27.7)
 8                Florida       118 (0.2)   5,231 (7.3)   18,889 (26.5)
 9                Georgia        71 (0.2)   2,832 (7.7)   10,185 (27.6)
 10                Hawaii         6 (0.3)     190 (9.5)      549 (27.4)
 11                 Idaho              —¶    187 (12.4)      477 (31.5)
 12            Illinois**        75 (0.2)   3,492 (9.1)   10,960 (28.4)
 13               Indiana        18 (0.2)    768 (10.1)    2,324 (30.4)
 14                  Iowa        12 (0.3)    357 (10.0)      957 (26.8)
 15                Kansas        12 (0.2)     632 (9.2)    2,148 (31.2)
 16              Kentucky        11 (0.3)     294 (8.0)    1,071 (29.2)
 17             Louisiana        26 (0.3)     726 (8.9)    2,302 (28.3)
 18                 Maine         5 (0.2)     198 (9.8)      585 (29.0)
 19         Massachusetts        28 (0.2)   1,306 (7.0)    4,613 (24.8)
 20              Michigan        51 (0.2)   2,328 (8.6)    7,538 (27.7)
 21             Minnesota        26 (0.3)     823 (8.3)    2,693 (27.1)
 22           Mississippi         7 (0.2)     295 (9.2)      970 (30.4)
 23              Missouri         5 (0.3)     141 (9.6)      422 (28.7)
 24               Montana         5 (0.3)    157 (10.0)      458 (29.2)
 25              Nebraska         7 (0.3)     187 (9.0)      625 (30.2)
 26                Nevada        19 (0.2)     691 (8.6)    2,200 (27.2)
 27          New Jersey††        50 (0.2)   1,958 (8.8)    5,648 (25.5)
 28            New Mexico        22 (0.6)    507 (13.8)    1,111 (30.3)
 29              New York       186 (0.2)   6,919 (8.8)   20,238 (25.8)
 30         New York City       109 (0.2)   4,052 (8.1)   12,471 (25.1)
 31        New York State        77 (0.3)  2,867 (10.0)    7,767 (27.1)
 32        North Carolina        60 (0.2)   2,252 (8.3)    7,768 (28.8)
 33          North Dakota           0 (—)    121 (10.8)      349 (31.1)
 34                  Ohio        63 (0.3)   1,737 (8.6)    5,887 (29.3)
 35              Oklahoma        89 (1.8)     440 (8.8)    1,517 (30.4)
 36                Oregon        19 (0.2)     837 (9.6)    2,373 (27.3)
 37          Pennsylvania        71 (0.2)   2,474 (8.0)    8,435 (27.2)
 38          Rhode Island              —¶     185 (8.8)      611 (29.1)
 39        South Carolina        10 (0.2)     499 (9.8)    1,403 (27.5)
 40          South Dakota              —¶            —¶      129 (31.2)
 41             Tennessee        17 (0.2)     830 (8.6)    2,884 (29.8)
 42                 Texas       106 (0.2)   5,041 (8.8)   16,647 (29.1)
 43                  Utah         6 (0.2)    371 (12.7)      915 (31.3)
 44               Vermont              —¶     108 (9.1)      305 (25.6)
 45              Virginia        25 (0.2)   1,108 (7.1)    4,162 (26.7)
 46            Washington        32 (0.2)   1,647 (9.6)    4,598 (26.7)
 47         West Virginia         8 (0.7)     115 (9.7)      377 (31.9)
 48             Wisconsin        17 (0.3)    690 (10.6)    1,917 (29.4)
 49               Wyoming              —¶            —¶        6 (19.4)
 50                 Total     1,410 (0.2)  53,049 (8.6)  171,043 (27.6)
 51       Abortion rate¶¶             0.4           6.0            19.0
 52     Abortion ratio***             873           348             275

                                                                  \
              25–29           30–34          35–39           ≥40
            No. (%)         No. (%)        No. (%)       No. (%)
 0     1,783 (29.7)    1,119 (18.6)      565 (9.4)     183 (3.0)
 1       363 (28.6)      246 (19.4)     137 (10.8)            —¶
 2     3,631 (27.7)    2,446 (18.7)   1,420 (10.8)     482 (3.7)
 3       901 (30.4)      513 (17.3)      260 (8.8)      90 (3.0)
 4     2,557 (28.4)    1,735 (19.3)     948 (10.5)     319 (3.5)
 5     2,600 (28.8)    1,885 (20.9)   1,042 (11.5)     323 (3.6)
 6       574 (28.1)      388 (19.0)     209 (10.2)      48 (2.4)
 7     1,388 (30.5)      870 (19.1)     483 (10.6)     152 (3.3)
 8    20,741 (29.1)   15,051 (21.1)   8,425 (11.8)   2,907 (4.1)
 9    11,361 (30.8)    7,254 (19.7)   3,932 (10.7)   1,272 (3.4)
 10      546 (27.3)      381 (19.0)     238 (11.9)      93 (4.6)
 11      378 (25.0)      252 (16.7)     161 (10.6)            —¶
 12   11,819 (30.6)    7,166 (18.6)    3,813 (9.9)   1,255 (3.3)
 13    2,168 (28.4)    1,354 (17.7)      745 (9.8)     260 (3.4)
 14    1,000 (28.1)      679 (19.0)     401 (11.2)     159 (4.5)
 15    1,932 (28.0)    1,239 (18.0)     692 (10.0)     239 (3.5)
 16    1,069 (29.2)      719 (19.6)     384 (10.5)     116 (3.2)
 17    2,521 (31.0)    1,534 (18.8)      782 (9.6)     253 (3.1)
 18      534 (26.4)      381 (18.9)     254 (12.6)      63 (3.1)
 19    5,313 (28.6)    4,028 (21.7)   2,390 (12.9)     910 (4.9)
 20    8,697 (32.0)    5,201 (19.1)    2,545 (9.4)     831 (3.1)
 21    2,837 (28.6)    2,015 (20.3)   1,205 (12.1)     336 (3.4)
 22    1,003 (31.4)      574 (18.0)      276 (8.6)      69 (2.2)
 23      436 (29.6)      253 (17.2)     156 (10.6)      58 (3.9)
 24      454 (29.0)      269 (17.2)     161 (10.3)      64 (4.1)
 25      534 (25.8)      400 (19.3)     234 (11.3)      81 (3.9)
 26    2,257 (27.9)    1,630 (20.2)     918 (11.4)     363 (4.5)
 27    6,497 (29.3)    4,462 (20.1)   2,604 (11.7)     959 (4.3)
 28      921 (25.1)      621 (16.9)     379 (10.3)     104 (2.8)
 29   22,267 (28.4)   16,014 (20.4)   9,438 (12.0)   3,386 (4.3)
 30   14,159 (28.4)   10,414 (20.9)   6,260 (12.6)   2,318 (4.7)
 31    8,108 (28.3)    5,600 (19.5)   3,178 (11.1)   1,068 (3.7)
 32    8,270 (30.6)    5,095 (18.9)    2,687 (9.9)     880 (3.3)
 33      326 (29.1)      189 (16.9)      107 (9.5)      29 (2.6)
 34    6,057 (30.1)    3,720 (18.5)    1,983 (9.9)     655 (3.3)
 35    1,384 (27.7)      901 (18.0)      491 (9.8)     172 (3.4)
 36    2,326 (26.8)    1,702 (19.6)   1,049 (12.1)     382 (4.4)
 37    9,529 (30.7)    6,188 (19.9)   3,244 (10.5)   1,077 (3.5)
 38      584 (27.8)      411 (19.6)     222 (10.6)            —¶
 39    1,500 (29.4)      961 (18.8)     544 (10.7)     184 (3.6)
 40      117 (28.3)       61 (14.7)      45 (10.9)            —¶
 41    2,982 (30.8)    1,791 (18.5)      913 (9.4)     275 (2.8)
 42   16,327 (28.5)   10,907 (19.0)   6,152 (10.7)   2,095 (3.7)
 43      761 (26.0)      470 (16.1)     305 (10.4)      94 (3.2)
 44      322 (27.0)      247 (20.7)     153 (12.8)            —¶
 45    4,626 (29.7)    3,186 (20.4)   1,869 (12.0)     605 (3.9)
 46    4,723 (27.4)    3,367 (19.5)   2,095 (12.2)     765 (4.4)
 47      320 (27.0)      194 (16.4)     136 (11.5)      33 (2.8)
 48    1,806 (27.7)    1,202 (18.5)      637 (9.8)     242 (3.7)
 49       10 (32.3)        8 (25.8)       6 (19.4)            —¶
 50  181,052 (29.3)  121,279 (19.6)  67,835 (11.0)  23,121 (3.7)
 51            18.6            13.0            7.4           2.7
 52             194             132            145           224

    Total abortions reported by known age
    Total abortions reported by known age
       No. (% of all reported abortions)§
 0                          6,006 (100.0)
 1                          1,270 (100.0)
 2                         13,093 (100.0)
 3                           2,960 (99.9)
 4                           8,994 (99.9)
 5                           9,040 (98.2)
 6                          2,042 (100.0)
 7                          4,551 (100.0)
 8                          71,362 (99.2)
 9                         36,907 (100.0)
 10                         2,003 (100.0)
 11                          1,512 (99.9)
 12                         38,580 (99.5)
 13                         7,637 (100.0)
 14                         3,565 (100.0)
 15                         6,894 (100.0)
 16                         3,664 (100.0)
 17                         8,144 (100.0)
 18                         2,020 (100.0)
 19                        18,588 (100.0)
 20                         27,191 (99.5)
 21                          9,935 (99.9)
 22                         3,194 (100.0)
 23                         1,471 (100.0)
 24                         1,568 (100.0)
 25                         2,068 (100.0)
 26                          8,078 (96.0)
 27                        22,178 (100.0)
 28                          3,665 (93.0)
 29                         78,448 (99.8)
 30                        49,783 (100.0)
 31                         28,665 (99.5)
 32                         27,012 (94.9)
 33                         1,121 (100.0)
 34                        20,102 (100.0)
 35                         4,994 (100.0)
 36                         8,688 (100.0)
 37                        31,018 (100.0)
 38                         2,098 (100.0)
 39                         5,101 (100.0)
 40                           414 (100.0)
 41                          9,692 (99.7)
 42                        57,275 (100.0)
 43                         2,922 (100.0)
 44                          1,191 (99.7)
 45                         15,581 (99.9)
 46                         17,227 (99.8)
 47                         1,183 (100.0)
 48                         6,511 (100.0)
 49                            31 (100.0)
 50                      618,789 (99.5)§§
 51                                   NaN
 52                                   NaN  ,
                         Age group (yrs)                                 Year  \
                         Age group (yrs)                                 2010
 0   Reported abortions by known age (%)  Reported abortions by known age (%)
 1                                   <15                                  0.5
 2                                 15–19                                 14.6
 3                                 20–24                                 32.9
 4                                 25–29                                 24.5
 5                                 30–34                                 15.3
 6                                 35–39                                  8.9
 7                                   ≥40                                  3.4
 8                         Abortion rate                        Abortion rate
 9                                   <15                                  1.0
 10                                15–19                                 11.7
 11                                20–24                                 26.8
 12                                25–29                                 20.2
 13                                30–34                                 13.2
 14                                35–39                                  7.6
 15                                  ≥40                                  2.8
 16                       Abortion ratio                       Abortion ratio
 17                                  <15                                  848
 18                                15–19                                  332
 19                                20–24                                  291
 20                                25–29                                  184
 21                                30–34                                  138
 22                                35–39                                  171
 23                                  ≥40                                  274

In [4]:
url2 = "https://www.guttmacher.org/report/pregnancies-births-abortions-in-united-states-1973-2017"

tables2 = pd.read_html(url2)

tables2

HTTPError: HTTP Error 403: Forbidden